install:
- source ./texlive_install.sh
cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"
script:
- mkdir _build
- travis_wait 3 pdflatex -output-directory _build ./MatanColloc02.tex
- travis_wait 3 pdflatex -output-directory _build ./MatanColloc02.tex
deploy:
  provider: releases
  api_key:
    secure: VjMpFNAf6omHs9YZkHsbty/FOqvJSkE1Vp8nJs0WHsvsVMwhIgqb0uwMTpVh0X61bRXbRu3kAJjl/UQ/TY9JND+5kxWYPgzicpi8K0Ap7soMD+eZ/X4pCr3Q2chc+FC/muQDlPZJX/yVVhmDZ7Uv+NnqJjog3isot1uhn+ll2X6cd5dDiNhPmk65JdhumUqTk8KvhrFYowt8uWfqlRMt7LZoAj2kC2QldtiAo4N3AXf1PV/iD8i/u0R6fRHugWVG5RnkRRAY3KeniHnvZJz9Op+0SNdPeNOMX3E3ml/L8n2dngpL9fhc5ZFaa5d2nCTPYjLRloRwB4aFqYvEMy5/Kz4O2MjLXBNX8hSxRi9xUoCeknSRx25eFaIJv0uMf0Fccp9EPUuagoKFZS6Wrm+aGDbYO3ZmQmd9ydZ+9lpzzpk0nI27Wm6JhkEPbSgs/Kew8VJDaATIvqEob9ohNYuPASrzZwEGYuJUtOAhBUchtxLQN2MVi/pkLqjWe9b8MrraRuoEA6E1PTLWcNhg7SXsycsw63gqWF7R3y8jnS1OhHXRszVf76FTYB8loCDWLy1sWCoa3wl17EThyMR0bba4hVYCtjEag6R5EVe171QYvKZIeaZEB2m/Y5YryjQCQsLVMEvHXwr5lNbBUZEfuT7nWJreI7SQlGqToM0ecHJ5Vu4=  
  file: _build/MatanColloc02.pdf
  draft: true
  on:
    repo: bot-mne-v-rot/math-analysis-1course-1sem
  skip_cleanup: 'true'