install:
- source ./texlive_install.sh
cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"
script:
- mkdir _build
- travis_wait 3 pdflatex -output-directory _build ./MatanColloc02.tex
- travis_wait 3 pdflatex -output-directory _build ./MatanColloc02.tex
deploy:
  provider: releases
  api_key:
    secure: VeS+VRH1qiivwCSy/H+M4Rt+vs4IMAilTlefDIU5P0RdyDlnN/+B7aX7xs3Usw/QlWPl3N0gZoyqm69gZhnmMJv9vV9cJQQZxmfyP/hEX2qymQCJFefMrOsD2h3txoA9Ve4VRItCj7ibGuiC68gmvSMjQaeAvfWk8gQrPt4PzpYbg2CDtnvDLcPPjLpOynDTZuPKf/0MxdIR7PfzPCtGViq5HeYuiXyT7FbHsR//DD09m6mOd8bhxgpEOj88fS84XwDj2770SvPYjq/pQsSmbEwvhNDpevMRaWWB1pTSwZe/7hD22B3ScbwZivh1sbOIBAJaCEST9M9PmaZ0IAmYidBlfLU+r97WaFipwiC9Q98bXsBc3fAx/b5/bAgiSerSDx9yz18ieHXpl909B1wa/u6bdk99NW061mVFbfKOmXktghkKk9T6yAJTwKDqSv0nnQH7zZw1wtamNaMTn450/UTefb1PK8JmOMPZwKcUbK8K0vNtar6UW5Bl4zeTM+phXPisBOZKrUnv8GJRYULrxOGDIRL2uWEeYvvl8Rw+1VicHht6RSRa9ytugpe9mMgi3HbFG+ohZVrOqZWq/Sd14jKx+V5rJDg2qsLYS7jQGkbNtk37Wuk3hF+RbWddVLZo10uUfZogrgUy7Z3fJnJMQ5y+jlXcZlgcV3YDd4NJ/YI=
  file: _build/MatanColloc02.pdf
  draft: true
  on:
    repo: bot-mne-v-rot/math-analysis-1course-1sem
  skip_cleanup: true