install:
- source ./texlive_install.sh
cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"
script:
- mkdir _build
- travis_wait 3 pdflatex -output-directory _build ./MatanColloc02.tex
- travis_wait 3 pdflatex -output-directory _build ./MatanColloc02.tex
deploy:
  provider: releases
  api_key:
    secure: m6LlA/pAC+Mn0gMVPg5qEGtkaVrN2jTJdc9e/CXB0Ys/hz0GHIlJFWilG/JEYg2GWK7JxWpXlYt22jZqn+EJDwfkJrqGvzQc683ULNYmSRDmXUYjYVyhU5Ijj+t/SPz8ah7pl2aGMvl0vd6ihb4wamjyJ7cY7fsA+HP5wnhC1z+MA2YfEU0KVd0c+95Uvgz788j3Em0fboKOVMKlQ1au8hnefvNvSFOWk1ixwW6+BMCx/oUf97LVqKefnbBHImpCdul7J5CsLB7pCMRtLT4zONhbv+o4ZP5EidbgOQhUPpJam9kHWiv88sbziTWbWuNTaLOiHV6lopmCbkMpyxApoxOOf9WUr/e2VpBLfkZzed+dk8ANBhpsrOGSgt8CoR1eQCKoTBM57LwOeMl/HRpPg6WeoNkAfPZmSTYbRbr9oa616wf6wSo+wyS/FFOVSCWF2BBElCGVhXtxpvqMyWE4aS4dGubZXFkgjukZDlCwqy/OyErrfhKl8Z4yz35RRNaOk5qO425YFaCQjJZfOmM0y1MKPoyb5WD08LQ44QZHZ5A5hclWMz6slnZHf3uegrGUlK4o6LjP2QQjbU4Ie3gVlGPLziEWstauCLBN5ZUXQkhep10y/Qjuzc4Bjo0pqtvbwOE2XAJeLhVAVkPTY9FPjB5tEDqg4tX7h4Gm8yHviq8=
  file: _build/MatanColloc02.pdf
  draft: true
  on:
    repo: bot-mne-v-rot/math-analysis-1course-1sem
  skip_cleanup: 'true'