install:
- source ./texlive_install.sh
cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"
script:
- mkdir _build
- travis_wait 3 pdflatex -output-directory _build ./MatanColloc02.tex
- travis_wait 3 pdflatex -output-directory _build ./MatanColloc02.tex
deploy:
  provider: releases
  api_key:
    secure: LAfTz4xcqGMmnYClMJAc7QO/nDW0Oz2KLU5srnmX0+WVv+bfoZcuHUs/7sNjOeARnosq2hlt8tXuIPNpPyhsOve6ekJun7XzY44KPCLNuu/e/X1lCsxKfAYDM+gwg1TWZA4jOoVMLHuNrm8sa9csHnNPPN9yQgDlBl8D1sjd1zPwg8BFjGp3v6T6VnHVJPQ+YkKEweMTTvslkQyyzMhLJyzB2Goi0RIdf5T/pwm/uf7vgxdHXwLBPwAN/z0jPsgOvTlFNvkdS7AELh1Hdeb/3Sdhm/1uo3IIbFA/fJVrMLsSwMAuPXLO9weByGzs9ezbXWcbLRWsgbrfwbfTCRSZgIsylBT0TOeWjsOQIOiQO4OQl4HEo2D1jchVNp8j5LIN3P9iXvGqtXRKy9MDth5zcGF8gzXT1KgUINuaLDjAS8JhiOc5J1oc0vj3wnuBB4GPgpFz9ZloUw6qIMKoOaRIrOMYRdJvH7Etr1kHs9Bj/FRJRXgCgnkUGqaI3GHbmRdBqm6+qZRcaLETLJbWKfIGb5X11HCNUNjfxAxgpZd8/sdofNpBg7xbEi9egyAWaFdErl9NQhd60093GAhBHzlmWfpb2Ag6Z9VIVqDN3N+8EiaGrV1s1zVxD8Q4yer/U7F1R3JDUzyTYs2a1tLxVSpTZ/q9nQHS/IyiB4zQ0GFB+aU=
  file: _build/MatanColloc02.pdf
  draft: true
  on:
    repo: bot-mne-v-rot/math-analysis-1course-1sem
  skip_cleanup: 'true'